### PR TITLE
upgrade dependencies

### PR DESCRIPTION
**Pull request by nikooo777**
This PR brings in upgrades to the packages used in the project as github is warning about vulnerabilities.
In more detail, the following upgrades were performed:

```
 axios                    ^0.16.1  →  ^0.18.0 
 redux                     ^3.7.2  →   ^4.0.0 
 winston                   ^2.3.1  →   ^3.0.0 
 chai-http                 ^3.0.0  →   ^4.0.0 
 eslint                    4.18.0  →   4.19.1 
 eslint-config-standard   ^10.2.1  →  ^11.0.0 
 eslint-plugin-node        ^4.2.3  →   ^6.0.1 
 husky                    ^0.13.4  →  ^0.14.3 
 mocha                     ^4.0.1  →   ^5.2.0 
 regenerator-transform    ^0.12.4  →  ^0.13.0 
 sequelize-cli           ^3.0.0-3  →   ^4.0.0 

```

No tests were run, some major upgrades might not be compatible at all. I'd like the help of someone actively developing the project to take a look

### CODE REVIEW

**Comment by billbitt** [comment]
thanks @nikooo777 I'll test

**Comment by billbitt** [comment]
I tested this today. It seems to be working, except the winston logger is throwing a warning `Attempt to write logs with no transports` when logging.  This doesn't seem to be an issue with winston, because it happens when I downgraded it back to `2.3.1` as well.  I'm not sure what change created this.  I'd like to merge the `lbryio/www.spee.ch` repo with this repo before debugging this, as it may have to do with the relative paths used in that repo to get resources from this package.

**Comment by nikooo777** [comment]
Absolutely! let me know if you want to do a session together so we can debug it with 4 eyes :)

**Comment by billbitt** [comment]
@nikooo777, are you familiar with https://github.com/greenkeeperio/greenkeeper ?

**Comment by nikooo777** [comment]
I am not, but that looks like a nice tool we could implement! As long as it doesn't automatically merge the new dependencies though.

**Pull request merged**
