### PR TITLE
Social Buttons, Lbry link, auto-scroll description

### PR DESCRIPTION
**Pull request by MSFTserver**
- added auto-scrolling description
- added social media share links
- added lbry direct link
- re-arranged layout to have description under title

### CODE REVIEW

**Comment by MSFTserver** [comment]
wait on this till you add the PR @billbitt and i add the `.` between filename and extension, or if we dont use that pr but i think we will go ahead and push this

**Comment by MSFTserver** [comment]
im not seeing the conflicts are these false lol @billbitt

**Comment by MSFTserver** [comment]
those <br> are valib but if it doesnt like it i guess ill change it back to the confusing <b /> and </ b> you had going on

**Comment by MSFTserver** [comment]
added twitter cards not 100% if video one is correct but we can play around with it
```
<!-- Twitter Card data -->
	<meta name="twitter:site" content="@LBRYio">
	<meta name="twitter:domain" content="spee.ch">
	<meta name="twitter:title" content="{{fileInfo.name}}">
	<meta name="twitter:description" content="Spee.ch - Decentralized Image Hosting using Lbry Protocol">
	<!-- Twitter Summary card images must be at least 120x120px -->
	{{#ifConditional fileInfo.fileType '===' 'video/mp4'}}
	<meta name="twitter:card" content="player">
	<meta name="twitter:player" content="https://spee.ch/{{fileInfo.name}}">
	<meta name="twitter:player:width" content="735">
  <meta name="twitter:player:height" content="449">
	<meta name="twitter:image" content="https://spee.ch/test.png">
	<meta name="twitter:image:width" content="735">
	<meta name="twitter:image:height" content="449">
	{{else}}
	<meta name="twitter:card" content="summary_large_image">
	<meta name="twitter:image" content="https://spee.ch/{{fileInfo.claimId}}/{{fileInfo.name}}.{{fileInfo.fileExt}}">
	<meta name="twitter:image:width" content="735">
	<meta name="twitter:image:height" content="449">
	{{/ifConditional}}
```

**Comment by MSFTserver** [comment]
we could move this to testing branch till we figure out the video card its a little trickier than image since they need a thumbnail and some extra parameters to through with it and there isnt very good docs about the player card or examples to go off of

**Comment by MSFTserver** [comment]
if you cant get this one to work or its to much work to resolve these conflicts i can make anew pr that should be better after all this auth changes

**Comment by MSFTserver** [comment]
better format for lbry app direct link is `lbry://{{fileInfo.name}}#{{fileInfo.claimId}}`

**Comment by MSFTserver** [comment]
did we move `generalstyle.css` to `bem.css`?

**Comment by billbitt** [comment]
@MSFTserver yeah, and in fact I'm working on a few more changes to the CSS to restructure it for the redesign.  Maybe hold off until Monday-ish?  I can show you what I'm working on pretty soon and then we can find the best way to incorporate what you've done.

**Comment by MSFTserver** [comment]
yea sounds good i can wait, shuldnt be too much of hassle ive been following what your implementing not to much effects what ive done but i know jeremy asked about the profile links adn some other things where he would like links so i would probably want some things in there also with couple new pages that youve made with the auth stuff

**Comment by MSFTserver** [comment]
and i pretty much deleted this repo off my github and re-forked it so i can wait till yoru done then pull the proper stuff cause mine is all over the place right now cant merge anything lol

**Comment by MSFTserver** [comment]
so we can close if you want and ill make cleaner PR for this

**Comment by billbitt** [comment]
will do, and once this is done and signed off by jeremy we should have a much more dependable foundation to build on in the future without having to worry about things changing too much.

**Comment by billbitt** [comment]
closing so @MSFTserver can open new PR

**Pull request closed without merging**
