### PR TITLE
Spee.ch FAQ

### PR DESCRIPTION
**Pull request by LavRadis**
The first version of spee.ch FAQ.

### CODE REVIEW

**Comment by skhameneh** [comment]
Hey @tzarebczan and @jsigwart, do you have feedback?

@heymattsokol I see this
> This should replace the current copy on the right side of https://spee.ch/about.

Creating a markdown file won't have any impact on that content.

**Comment by heymattsokol** [comment]
I understand. @LavRadis told me that we should only update the markdown file. Lav, what is your rationale?

**Comment by jsigwart** [comment]
I agree that the About page would be a good place to add this content so as to keep the site structure simple.

**Comment by LavRadis** [comment]
Hey guys, I asked @tzarebczan and he told me to it like this first. Also, the initial set up of this PR was made in coordination with @billbitt  I don't know what was the plan on how to use it further.  Sure, you can use it however you see fit.

**Comment by heymattsokol** [comment]
@tzarebczan Tom, can you please explain why you want us to put it in a markdown file rather than add it to the site proper? Trying to get to the bottom of this.

**Comment by tzarebczan** [comment]
Because markdown files are universal and can be put on another site if this moves. I'll leave it up to @daovist and @skhamenah

**Comment by daovist** [comment]
I support markdown for portability as @tzarebczan mentioned.

**Comment by heymattsokol** [comment]
@daovist We should do both then, ya? Markdown file for portability AND update the about page to include the new FAQ text? Or am I misunderstanding?

**Comment by skhameneh** [comment]
@daovist @tzarebczan maybe we should add a generator for Markdown to Speed.ch

Whatever route we want to take, we should avoid having duplicate/conflicting/fragmented content.
I'm fine with adding this into the repo now, but we'll need a clear path forward with an issue filed.

**Comment by daovist** [comment]
@heymattsokol yes the markdown looks good. You can add the new content to the about page manually for now also and I will make an issue to add markdown to speech and use the markdown content on the about page.

**Comment by heymattsokol** [comment]
@daovist Sounds good. I'll add that content to the about page in the next couple of days. Should we merge the PR with the markdown file first? I'm not sure who has authority to do that, since Bill used to be the guy.

**Comment by daovist** [comment]
@skhameneh will be handling spee.ch merges but do tag me for review in future PRs

I'm not picky about merging this now vs waiting until the about page is updated

**Comment by kauffj** [comment]
@robvsmith can you review this and mark it approved if it looks good to you, but not merge it? If you approve, then assign back to @daovist.

@LavRadis apologies for delay on this.

**Comment by daovist** [comment]
thank you for the copy @LavRadis @heymattsokol 

I used it in a [new PR](https://github.com/lbryio/spee.ch/pull/635) with a FAQ page linked from the about page

**Pull request closed without merging**
